// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqkY2x5Xo0TTXJ8Sr-7mIwW-rR0VwHjGk',
    appId: '1:768865102547:web:f5aeebca67123adacc4226',
    messagingSenderId: '768865102547',
    projectId: 'flutter-67fc8',
    authDomain: 'flutter-67fc8.firebaseapp.com',
    storageBucket: 'flutter-67fc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_Q5KkAPr-ajdcmnPNUxX8aK1uWn3-oqI',
    appId: '1:768865102547:android:efdde5ee368412decc4226',
    messagingSenderId: '768865102547',
    projectId: 'flutter-67fc8',
    storageBucket: 'flutter-67fc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5I1xoRo-EWWqsqjGgqKAXD-pX0_GRWjk',
    appId: '1:768865102547:ios:32d3e963335acee8cc4226',
    messagingSenderId: '768865102547',
    projectId: 'flutter-67fc8',
    storageBucket: 'flutter-67fc8.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5I1xoRo-EWWqsqjGgqKAXD-pX0_GRWjk',
    appId: '1:768865102547:ios:1f1c6c0b582f5359cc4226',
    messagingSenderId: '768865102547',
    projectId: 'flutter-67fc8',
    storageBucket: 'flutter-67fc8.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
