// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8bLeHCw-jAzkxlUimCPtQZvXS0uyJvE',
    appId: '1:787688906709:web:1eef49c653dbe11b78e75c',
    messagingSenderId: '787688906709',
    projectId: 'efreifluttercours1',
    authDomain: 'efreifluttercours1.firebaseapp.com',
    storageBucket: 'efreifluttercours1.appspot.com',
    measurementId: 'G-X5ML9TZSSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkL46wOqX08fvqEpSRYjGHwHLBVWfQi_s',
    appId: '1:787688906709:android:bc8f7b598824dc9678e75c',
    messagingSenderId: '787688906709',
    projectId: 'efreifluttercours1',
    storageBucket: 'efreifluttercours1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuBp_71wGqG4EmkRQQGrbiXvHJXxgYtQI',
    appId: '1:787688906709:ios:1004bb100f6a28d378e75c',
    messagingSenderId: '787688906709',
    projectId: 'efreifluttercours1',
    storageBucket: 'efreifluttercours1.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuBp_71wGqG4EmkRQQGrbiXvHJXxgYtQI',
    appId: '1:787688906709:ios:4c44e5266c74315b78e75c',
    messagingSenderId: '787688906709',
    projectId: 'efreifluttercours1',
    storageBucket: 'efreifluttercours1.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
